#!/usr/bin/env python3
"""
generate_env.py — Mapea config.json → .env.admin + .env.diario
Corre durante /culver-bootstrap-vps para generar los archivos .env en el VPS.

Uso:
  python3 scripts/generate_env.py ~/.culver/config.json [output_dir]
  # output_dir defaults to current directory
"""

import json
import sys
from pathlib import Path


def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return json.load(f)


def _common(config: dict) -> tuple:
    """Returns shared config sections."""
    user = config.get("user", {})
    agent = config.get("agent", {})
    vps = config.get("vps", {})
    telegram = config.get("telegram", {})
    github = config.get("github", {})
    llm = config.get("llm", {})
    personal_vault = config.get("personal_vault", {})
    agent_vault = config.get("agent_vault", {})
    culver_os_dir = vps.get("culver_os_dir", "/root/culver-os")
    return user, agent, vps, telegram, github, llm, personal_vault, agent_vault, culver_os_dir


def generate_admin_env(config: dict) -> str:
    user, agent, vps, telegram, github, llm, personal_vault, agent_vault, culver_os_dir = _common(config)
    bots = telegram.get("bots", {})
    admin_bot = bots.get("admin", {})
    paperclip = config.get("paperclip", {})
    pcp_agents = paperclip.get("agents", {})
    pcp_admin = pcp_agents.get("admin", {})

    lines = [
        "# Generated by generate_env.py — do not edit manually",
        f"AGENT_NAME={agent.get('name', 'Admin')}",
        f"BRAIN_NAME={agent.get('brain_name', 'culver')}",
        f"TELEGRAM_TOKEN={admin_bot.get('token', '')}",
        f"GROUP_ID={telegram.get('group_id', '')}",
        f"ADMIN_THREAD_ID={admin_bot.get('thread_id', '')}",
        f"GEMINI_API_KEY={llm.get('key', '')}",
        f"CULVER_OS_DIR={culver_os_dir}",
        f"CHROMA_HOST=localhost",
        f"CHROMA_PORT=8000",
        f"BRAIN_NAME={agent.get('brain_name', 'culver')}",
        f"GITHUB_USERNAME={github.get('username', '')}",
        f"GITHUB_PAT={github.get('pat', '')}",
        f"USER_NAME={user.get('name', '')}",
        f"USER_TIMEZONE={user.get('timezone', 'America/Los_Angeles')}",
        f"PERSONAL_VAULT_PATH={personal_vault.get('local_path', '')}",
        f"AGENT_VAULT_PATH={agent_vault.get('local_path', '')}",
        f"DAILY_NOTES_SUBDIR={personal_vault.get('daily_notes_dir', 'Daily Notes')}",
        f"WEEKLY_REVIEWS_SUBDIR={personal_vault.get('weekly_reviews_dir', 'Weekly Reviews')}",
        f"PCP_TOKEN={pcp_admin.get('token', '')}",
        f"PCP_AGENT_ID={pcp_admin.get('id', '')}",
    ]
    return "\n".join(lines) + "\n"


def generate_diario_env(config: dict) -> str:
    user, agent, vps, telegram, github, llm, personal_vault, agent_vault, culver_os_dir = _common(config)
    bots = telegram.get("bots", {})
    diario_bot = bots.get("diario", {})
    paperclip = config.get("paperclip", {})
    pcp_agents = paperclip.get("agents", {})
    pcp_diario = pcp_agents.get("diario", {})

    lines = [
        "# Generated by generate_env.py — do not edit manually",
        f"TELEGRAM_TOKEN={diario_bot.get('token', '')}",
        f"GROUP_ID={telegram.get('group_id', '')}",
        f"DIARIO_THREAD_ID={diario_bot.get('thread_id', '')}",
        f"GEMINI_API_KEY={llm.get('key', '')}",
        f"CULVER_OS_DIR={culver_os_dir}",
        f"CONFIG_PATH={culver_os_dir}/config.json",
        f"DIARIO_STATE_FILE={culver_os_dir}/diario_state.json",
        f"CHROMA_HOST=localhost",
        f"CHROMA_PORT=8000",
        f"BRAIN_NAME={agent.get('brain_name', 'culver')}",
        f"GITHUB_USERNAME={github.get('username', '')}",
        f"GITHUB_PAT={github.get('pat', '')}",
        f"USER_NAME={user.get('name', '')}",
        f"USER_TIMEZONE={user.get('timezone', 'America/Los_Angeles')}",
        f"PERSONAL_VAULT_PATH={personal_vault.get('local_path', '')}",
        f"AGENT_VAULT_PATH={agent_vault.get('local_path', '')}",
        f"DAILY_NOTES_SUBDIR={personal_vault.get('daily_notes_dir', 'Daily Notes')}",
        f"WEEKLY_REVIEWS_SUBDIR={personal_vault.get('weekly_reviews_dir', 'Weekly Reviews')}",
        f"PCP_TOKEN={pcp_diario.get('token', '')}",
        f"PCP_AGENT_ID={pcp_diario.get('id', '')}",
    ]
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_env.py <config.json> [output_dir]")
        sys.exit(1)

    config_path = sys.argv[1]
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(".")

    config = load_config(config_path)

    admin_path = output_dir / ".env.admin"
    admin_path.write_text(generate_admin_env(config))
    print(f"✅ Generated {admin_path}")

    diario_path = output_dir / ".env.diario"
    diario_path.write_text(generate_diario_env(config))
    print(f"✅ Generated {diario_path}")


if __name__ == "__main__":
    main()
