#!/usr/bin/env python3
"""
generate_env.py — Mapea config.json → .env.admin (y otros .env si se expande).
Corre durante /culver-bootstrap-vps para generar los archivos .env en el VPS.

Uso:
  python3 scripts/generate_env.py ~/.culver/config.json /root/culver-os/.env.admin
"""

import json
import sys
from pathlib import Path


def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return json.load(f)


def generate_admin_env(config: dict) -> str:
    user = config.get("user", {})
    agent = config.get("agent", {})
    vps = config.get("vps", {})
    telegram = config.get("telegram", {})
    bots = telegram.get("bots", {})
    admin_bot = bots.get("admin", {})
    github = config.get("github", {})
    llm = config.get("llm", {})
    obsidian = config.get("obsidian", {})

    culver_os_dir = vps.get("culver_os_dir", "/root/culver-os")

    lines = [
        "# Generated by generate_env.py — do not edit manually",
        f"AGENT_NAME={agent.get('name', 'Admin')}",
        f"BRAIN_NAME={agent.get('brain_name', 'culver')}",
        f"TELEGRAM_TOKEN={admin_bot.get('token', '')}",
        f"GROUP_ID={telegram.get('group_id', '')}",
        f"ADMIN_THREAD_ID={admin_bot.get('thread_id', '')}",
        f"GEMINI_API_KEY={llm.get('gemini_key', '')}",
        f"CULVER_OS_DIR={culver_os_dir}",
        f"CHROMA_HOST=localhost",
        f"CHROMA_PORT=8000",
        f"GITHUB_USERNAME={github.get('username', '')}",
        f"GITHUB_PAT={github.get('pat', '')}",
        f"USER_NAME={user.get('name', '')}",
        f"USER_TIMEZONE={user.get('timezone', 'America/Los_Angeles')}",
        f"OBSIDIAN_VAULT_PATH={obsidian.get('vault_path', '')}",
        f"DAILY_NOTES_SUBDIR={obsidian.get('daily_notes_subdir', 'Daily Notes')}",
        f"WEEKLY_REVIEWS_SUBDIR={obsidian.get('weekly_reviews_subdir', 'Weekly Reviews')}",
    ]
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_env.py <config.json> [output_path]")
        sys.exit(1)

    config_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else ".env.admin"

    config = load_config(config_path)
    env_content = generate_admin_env(config)

    Path(output_path).write_text(env_content)
    print(f"✅ Generated {output_path}")


if __name__ == "__main__":
    main()
