"""
status-operativo.py — Generates index/status-operativo.md in the agent vault.

Summarizes the user's active projects, recent activity, and system status.
Runs twice weekly: Wed 12:25 UTC and Sun 15:40 UTC.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

env_path = Path(__file__).parent.parent / ".env.admin"
load_dotenv(env_path)
sys.path.insert(0, str(Path(__file__).parent.parent))

from tools.llm import call_llm
from tools.vault_writer import escribir_en_vault_sync


def load_config() -> dict:
    with open(Path(__file__).parent.parent / "config.json") as f:
        return json.load(f)


def get_recent_daily_notes(vault_path: Path, n: int = 7) -> str:
    daily_dir = vault_path / "Daily Notes"
    if not daily_dir.exists():
        return "(no daily notes found)"
    notes = sorted(daily_dir.glob("*.md"), reverse=True)[:n]
    combined = []
    for note in notes:
        combined.append(f"### {note.stem}\n{note.read_text(encoding='utf-8', errors='ignore')[:800]}")
    return "\n\n".join(combined) if combined else "(no recent daily notes)"


def main():
    config = load_config()
    user_name = config.get("user", {}).get("name", "the user")
    agent_name = config.get("agent", {}).get("name", "the agent")
    projects = config.get("projects", [])
    personal_vault = Path(os.environ.get("PERSONAL_VAULT_PATH", ""))

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Pull recent daily notes as context
    recent_notes = get_recent_daily_notes(personal_vault) if personal_vault.exists() else "(vault not available)"

    projects_list = "\n".join(f"- {p['name']}: {p.get('description', '')}" for p in projects)

    prompt = f"""You are generating a status operativo report for {user_name}'s personal AI system.

Active projects:
{projects_list}

Recent daily notes (last 7 days):
{recent_notes[:4000]}

Generate a structured status report in Markdown with these sections:
## Status General
(1-2 sentence system status)

## Proyectos Activos
(bullet per project: what's happening, what's next)

## Highlights de la Semana
(key wins, decisions, insights from daily notes)

## Pendientes Críticos
(top 3-5 action items that appear repeatedly or are overdue)

## Notas para {agent_name}
(context the AI agent should keep in mind for conversations this week)

Date: {today}
Write in the same language as the daily notes. Be concise and actionable."""

    content = call_llm(prompt)

    full_content = f"""---
title: Status Operativo — {today}
type: status
date: {today}
---

{content}

---
*Generated by status-operativo.py on {today}*
"""

    result = escribir_en_vault_sync(
        vault="agent",
        archivo="index/status-operativo.md",
        contenido=full_content,
        modo="actualizar",
        agente="status-operativo",
    )

    print(f"[status-operativo] {'✅' if result else '❌'} report for {today}")


if __name__ == "__main__":
    main()
