"""
vault-health.py — Generates a system health report and writes it to the agent vault.

Checks: systemd services, timers, ChromaDB, vault sync recency.
Runs daily at 13:30 UTC via systemd timer.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

env_path = Path(__file__).parent.parent / ".env.admin"
load_dotenv(env_path)

sys.path.insert(0, str(Path(__file__).parent.parent))

from tools.vault_writer import escribir_en_vault_sync


SERVICES = ["culver-bot", "chroma-server", "diario-bot", "finno-bot", "jobs-bot", "log-watcher"]
TIMERS = [
    "daily-note", "vault-ingest", "vault-health", "obsidian-brain-sync",
    "vault-brain-sync", "log-rotate", "status-operativo-wed", "status-operativo-sun",
    "weekly-planning", "weekly-fill", "weekly-digest", "perfil-identidad", "monthly-planning",
]


def check_service(name: str) -> tuple[str, str]:
    try:
        r = subprocess.run(
            ["systemctl", "is-active", name],
            capture_output=True, text=True, timeout=5,
        )
        status = r.stdout.strip()
        return ("✅", status) if status == "active" else ("❌", status)
    except Exception as e:
        return ("❌", str(e))


def check_timer(name: str) -> tuple[str, str]:
    try:
        r = subprocess.run(
            ["systemctl", "show", f"{name}.timer", "--property=LastTriggerUSec"],
            capture_output=True, text=True, timeout=5,
        )
        val = r.stdout.strip().replace("LastTriggerUSec=", "")
        if val in ("", "n/a"):
            return ("⚠️", "never triggered")
        return ("✅", val)
    except Exception as e:
        return ("⚠️", str(e))


def check_chroma() -> tuple[str, str]:
    try:
        import requests
        r = requests.get("http://localhost:8000/api/v1/heartbeat", timeout=3)
        return ("✅", "reachable") if r.status_code == 200 else ("❌", f"HTTP {r.status_code}")
    except Exception as e:
        return ("❌", str(e))


def build_report() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# System Health Report — {now}",
        "",
        "## Services",
        "",
    ]

    for svc in SERVICES:
        icon, status = check_service(svc)
        lines.append(f"- {icon} `{svc}`: {status}")

    lines += ["", "## Timers", ""]
    for timer in TIMERS:
        icon, status = check_timer(timer)
        lines.append(f"- {icon} `{timer}`: {status}")

    lines += ["", "## ChromaDB", ""]
    icon, status = check_chroma()
    lines.append(f"- {icon} `chroma-server`: {status}")

    lines += ["", "---", f"*Generated by vault-health.py at {now}*", ""]
    return "\n".join(lines)


def main():
    report = build_report()
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    file_path = f"index/supervisor-reports/health-{date_str}.md"

    result = escribir_en_vault_sync(
        vault="agent",
        archivo=file_path,
        contenido=report,
        modo="actualizar",
        agente="vault-health",
    )

    if result:
        print(f"[vault-health] ✅ report written to {file_path}")
    else:
        print(f"[vault-health] ❌ failed to write report")
        sys.exit(1)


if __name__ == "__main__":
    main()
