"""
weekly-digest.py — Generates a Weekly Intelligence Digest in the agent vault.

Compiles key intel from the past week: market updates, project decisions, opportunities.
Runs Sundays at 04:00 UTC.
"""

import json
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

from dotenv import load_dotenv

env_path = Path(__file__).parent.parent / ".env.admin"
load_dotenv(env_path)
sys.path.insert(0, str(Path(__file__).parent.parent))

from tools.llm import call_llm
from tools.vault_writer import escribir_en_vault_sync


def load_config() -> dict:
    with open(Path(__file__).parent.parent / "config.json") as f:
        return json.load(f)


def read_recent_wiki(agent_vault: Path, days: int = 7) -> str:
    wiki_path = agent_vault / "wiki"
    if not wiki_path.exists():
        return "(no wiki content yet)"
    cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
    pages = [f for f in wiki_path.rglob("*.md") if f.stat().st_mtime > cutoff]
    if not pages:
        return "(no new wiki pages this week)"
    combined = []
    for p in sorted(pages, key=lambda f: f.stat().st_mtime, reverse=True)[:10]:
        combined.append(f"### {p.stem}\n{p.read_text(encoding='utf-8', errors='ignore')[:400]}")
    return "\n\n".join(combined)


def main():
    config = load_config()
    agent_vault = Path(os.environ.get("AGENT_VAULT_PATH", ""))
    user_name = config.get("user", {}).get("name", "the user")
    projects = config.get("projects", [])
    projects_list = "\n".join(f"- {p['name']}: {p.get('description', '')}" for p in projects)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    week_num = datetime.now(timezone.utc).isocalendar()[1]

    recent_wiki = read_recent_wiki(agent_vault) if agent_vault.exists() else "(vault not available)"

    prompt = f"""You are generating a weekly intelligence digest for {user_name}.

Active projects:
{projects_list}

New wiki pages from this week:
{recent_wiki}

Generate a Weekly Intelligence Digest in Markdown:

## Executive Summary
(2-3 sentences: what mattered most this week)

## Por Proyecto
(for each project with activity: status + key development)

## Oportunidades Identificadas
(2-3 specific opportunities surfaced by this week's intel)

## Riesgos / Blockers
(2-3 items that could block progress next week)

## Recursos Útiles
(links, tools, or contacts mentioned in the wiki this week)

Date: Week {week_num}, {today}
Be specific and actionable. Write in the same language as the wiki content."""

    digest = call_llm(prompt)

    content = f"""---
title: Weekly Digest — Week {week_num} ({today})
type: weekly-digest
date: {today}
week: {week_num}
---

{digest}

---
*Generated by weekly-digest.py on {today}*
"""

    file_path = f"index/weekly-digest-{today}.md"
    result = escribir_en_vault_sync(
        vault="agent",
        archivo=file_path,
        contenido=content,
        modo="crear",
        agente="weekly-digest",
    )
    print(f"[weekly-digest] {'✅' if result else '❌'} {file_path}")


if __name__ == "__main__":
    main()
